export interface HangWord {
  word: string;
  hint: string;
}

export const HANGMAN_WORDS: HangWord[] = [
  { word: "COMPUTADORA", hint: "Dispositivo electrónico para procesar datos" },
  { word: "ELEFANTE", hint: "Animal terrestre más grande" },
  { word: "PARAGUAS", hint: "Objeto para protegerse de la lluvia" },
  { word: "BICICLETA", hint: "Vehículo de dos ruedas" },
  { word: "HELICOPTERO", hint: "Aeronave con hélices giratorias" },
  { word: "TELEFONO", hint: "Dispositivo para comunicarse a distancia" },
  { word: "GUITARRA", hint: "Instrumento musical de cuerdas" },
  { word: "AVENTURA", hint: "Experiencia emocionante o arriesgada" },
  { word: "BIBLIOTECA", hint: "Lugar donde se guardan libros" },
  { word: "CHOCOLATE", hint: "Dulce hecho de cacao" },
  { word: "VOLCAN", hint: "Montaña que expulsa lava" },
  { word: "PIRAMIDE", hint: "Estructura triangular antigua" },
  { word: "JIRAFA", hint: "Animal con cuello largo" },
  { word: "OCEANO", hint: "Gran masa de agua salada" },
  { word: "MURCIELAGO", hint: "Único mamífero que vuela" },
  { word: "ARCOIRIS", hint: "Fenómeno óptico con colores" },
  { word: "ESPADA", hint: "Arma blanca larga y afilada" },
  { word: "CASTILLO", hint: "Edificio fortificado medieval" },
  { word: "FAROLA", hint: "Poste con luz para calles" },
  { word: "PINTURA", hint: "Arte de aplicar color sobre superficies" },
  { word: "GLOBO", hint: "Objeto que se infla con aire o gas" },
  { word: "RELOJ", hint: "Dispositivo que mide el tiempo" },
  { word: "MARIPOSA", hint: "Insecto con alas coloridas" },
  { word: "SOMBRERO", hint: "Prenda para cubrir la cabeza" },
  { word: "PELICULA", hint: "Obra cinematográfica" },
  { word: "TORMENTA", hint: "Fenómeno meteorológico con truenos" },
  { word: "CANGURO", hint: "Marsupial saltador de Australia" },
  { word: "PIZARRA", hint: "Superficie para escribir con tiza" },
  { word: "COHETE", hint: "Vehículo espacial propulsado" },
  { word: "TELESCOPIO", hint: "Instrumento para observar estrellas" },
  { word: "CEREZA", hint: "Fruta roja pequeña con hueso" },
  { word: "PINGUINO", hint: "Ave que no vuela y vive en el hielo" },
  { word: "CARACOL", hint: "Molusco con concha espiral" },
  { word: "BALLENA", hint: "Mamífero marino más grande" },
  { word: "VIOLIN", hint: "Instrumento musical de cuatro cuerdas" },
  { word: "PAPEL", hint: "Material delgado hecho de celulosa" },
  { word: "SERPIENTE", hint: "Reptil sin patas" },
  { word: "PARQUE", hint: "Área verde pública" },
  { word: "CASCADA", hint: "Caída de agua natural" },
  { word: "CABALLO", hint: "Animal usado para montar" },
  { word: "BOMBERO", hint: "Persona que apaga incendios" },
  { word: "DINOSAURIO", hint: "Animal prehistórico extinto" },
  { word: "PLATANO", hint: "Fruta amarilla alargada" },
  { word: "TAMBOR", hint: "Instrumento musical de percusión" },
  { word: "ARBOL", hint: "Planta con tronco y ramas" },
  { word: "CANGREJO", hint: "Crustáceo con pinzas" },
  { word: "FARO", hint: "Torre con luz para navegación" },
  { word: "MONEDA", hint: "Pieza de metal para pagar" },
  { word: "LLAVE", hint: "Herramienta para abrir cerraduras" },
  { word: "PUENTE", hint: "Estructura que cruza un río" },
  { word: "BUFANDA", hint: "Prenda para el cuello en invierno" },
  { word: "MAPA", hint: "Representación gráfica de territorios" },
  { word: "CARRETILLA", hint: "Herramienta para transportar materiales" },
  { word: "PALOMA", hint: "Ave símbolo de paz" },
  { word: "CACTUS", hint: "Planta con espinas del desierto" },
  { word: "TROMPETA", hint: "Instrumento musical de viento" },
  { word: "PELOTA", hint: "Objeto esférico para jugar" },
  { word: "CARRETERA", hint: "Vía para vehículos" },
  { word: "MARTILLO", hint: "Herramienta para clavar" },
  { word: "TORTUGA", hint: "Reptil con caparazón" },
  { word: "CANDADO", hint: "Dispositivo de seguridad" },
  { word: "GAFAS", hint: "Accesorio para corregir la vista" },
  { word: "PALOMITAS", hint: "Snack hecho de maíz inflado" },
  { word: "SILLA", hint: "Mueble para sentarse" },
  { word: "COCHE", hint: "Vehículo automotor" },
  { word: "PALETA", hint: "Dulce de azúcar en un palo" },
  { word: "CIRCO", hint: "Espectáculo con payasos y animales" },
  { word: "PANTALON", hint: "Prenda de vestir para piernas" },
  { word: "BOTELLA", hint: "Recipiente para líquidos" },
  { word: "CASCABEL", hint: "Esfera metálica que suena" },
  { word: "MESA", hint: "Mueble con superficie plana" },
  { word: "GORILA", hint: "Primates grandes y fuertes" },
  { word: "PISTOLA", hint: "Arma de fuego pequeña" },
  { word: "CEREBRO", hint: "Órgano principal del sistema nervioso" },
  { word: "LAPIZ", hint: "Instrumento para escribir" },
  { word: "CABALLO", hint: "Animal usado para montar" },
  { word: "CANDELABRO", hint: "Soporte para velas" },
  { word: "PULPO", hint: "Molusco con ocho tentáculos" },
  { word: "CARRUAJE", hint: "Vehículo tirado por caballos" },
  { word: "GALLINA", hint: "Ave doméstica que pone huevos" },
  { word: "PIMIENTA", hint: "Condimento picante" },
  { word: "SANDIA", hint: "Fruta grande y jugosa" },
  { word: "TIGRE", hint: "Felino grande con rayas" },
  { word: "CANGURO", hint: "Marsupial saltador de Australia" },
  { word: "PALACIO", hint: "Residencia real o noble" },
  { word: "CABALLERO", hint: "Hombre noble a caballo" },
  { word: "GIRASOL", hint: "Planta que sigue al sol" },
  { word: "PINGUINO", hint: "Ave que no vuela y vive en el hielo" },
  { word: "CEREZA", hint: "Fruta roja pequeña con hueso" },
  { word: "TELESCOPIO", hint: "Instrumento para observar estrellas" },
  { word: "COHETE", hint: "Vehículo espacial propulsado" },
  { word: "PIZARRA", hint: "Superficie para escribir con tiza" },
  { word: "CANGURO", hint: "Marsupial saltador de Australia" },
  { word: "TORMENTA", hint: "Fenómeno meteorológico con truenos" },
  { word: "PELICULA", hint: "Obra cinematográfica" },
  { word: "SOMBRERO", hint: "Prenda para cubrir la cabeza" },
  { word: "MARIPOSA", hint: "Insecto con alas coloridas" },
  { word: "RELOJ", hint: "Dispositivo que mide el tiempo" },
  { word: "GLOBO", hint: "Objeto que se infla con aire o gas" },
  { word: "PINTURA", hint: "Arte de aplicar color sobre superficies" },
  { word: "FAROLA", hint: "Poste con luz para calles" },
  { word: "CASTILLO", hint: "Edificio fortificado medieval" },
  { word: "ESPADA", hint: "Arma blanca larga y afilada" },
  { word: "ARCOIRIS", hint: "Fenómeno óptico con colores" },
  { word: "MURCIELAGO", hint: "Único mamífero que vuela" },
  { word: "OCEANO", hint: "Gran masa de agua salada" },
  { word: "JIRAFA", hint: "Animal con cuello largo" },
  { word: "PIRAMIDE", hint: "Estructura triangular antigua" },
  { word: "VOLCAN", hint: "Montaña que expulsa lava" },
  { word: "CHOCOLATE", hint: "Dulce hecho de cacao" },
  { word: "BIBLIOTECA", hint: "Lugar donde se guardan libros" },
  { word: "AVENTURA", hint: "Experiencia emocionante o arriesgada" },
  { word: "GUITARRA", hint: "Instrumento musical de cuerdas" },
  { word: "TELEFONO", hint: "Dispositivo para comunicarse a distancia" },
  { word: "HELICOPTERO", hint: "Aeronave con hélices giratorias" },
  { word: "BICICLETA", hint: "Vehículo de dos ruedas" },
  { word: "PARAGUAS", hint: "Objeto para protegerse de la lluvia" },
  { word: "ELEFANTE", hint: "Animal terrestre más grande" },
  { word: "COMPUTADORA", hint: "Dispositivo electrónico para procesar datos" },
  { word: "DRAGON", hint: "Criatura mitológica que escupe fuego" },
  { word: "UNICORNIO", hint: "Caballo mitológico con cuerno" },
  { word: "FANTASMA", hint: "Espíritu o aparición" },
  { word: "HADA", hint: "Ser mágico pequeño con alas" },
  { word: "MAGO", hint: "Persona que hace trucos de magia" },
  { word: "BRUJA", hint: "Mujer con poderes mágicos" },
  { word: "VAMPIRO", hint: "Ser nocturno que bebe sangre" },
  { word: "LOBO", hint: "Animal salvaje similar al perro" },
  { word: "OSO", hint: "Animal grande y peludo" },
  { word: "LEON", hint: "Rey de la selva" },
  { word: "RINOCERONTE", hint: "Animal grande con cuerno" },
  { word: "HIPOPOTAMO", hint: "Animal grande que vive en ríos" },
  { word: "CEBRA", hint: "Animal con rayas blancas y negras" },
  { word: "KOALA", hint: "Marsupial que vive en eucaliptos" },
  { word: "ARMADILLO", hint: "Animal con caparazón duro" },
  { word: "ORNITORRINCO", hint: "Mamífero que pone huevos" },
  { word: "CAMELLO", hint: "Animal del desierto con joroba" },
  { word: "FLAMENCO", hint: "Ave rosada de patas largas" },
  { word: "PATO", hint: "Ave acuática con pico ancho" },
  { word: "CISNE", hint: "Ave acuática elegante y blanca" },
  { word: "AGUILA", hint: "Ave rapaz de gran tamaño" },
  { word: "BUHO", hint: "Ave nocturna con ojos grandes" },
  { word: "COLIBRI", hint: "Ave pequeña que bate alas rápido" },
  { word: "PAVO", hint: "Ave grande con cola en abanico" },
  { word: "GORRION", hint: "Ave pequeña y común" },
  { word: "CANARIO", hint: "Ave pequeña y amarilla" },
  { word: "LORO", hint: "Ave que puede imitar sonidos" },
  { word: "CUERVO", hint: "Ave negra inteligente" },
  { word: "GAVIOTA", hint: "Ave marina común" },
  { word: "PELICANO", hint: "Ave con bolsa en el pico" },
  { word: "PINGUINO", hint: "Ave que no vuela y vive en el hielo" },
  { word: "FOCA", hint: "Mamífero acuático juguetón" },
  { word: "LEONMARINO", hint: "Mamífero acuático con melena" },
  { word: "DELFIN", hint: "Mamífero acuático inteligente" },
  { word: "ORCA", hint: "Ballena asesina" },
  { word: "TIBURON", hint: "Pez grande con dientes afilados" },
  { word: "BALLENA", hint: "Mamífero marino más grande" },
  { word: "PULPO", hint: "Molusco con ocho tentáculos" },
  { word: "CALAMAR", hint: "Molusco con diez tentáculos" },
  { word: "MEDUSA", hint: "Animal marino gelatinoso" },
  { word: "ESTRELLA", hint: "Animal marino con forma de estrella" },
  { word: "ERIZO", hint: "Animal marino con púas" },
  { word: "CABALLITO", hint: "Pequeño pez con cabeza de caballo" },
  { word: "ANGUILLA", hint: "Pez alargado como serpiente" },
  { word: "SALMON", hint: "Pez que nada contra corriente" },
  { word: "TRUCHA", hint: "Pez de agua dulce" },
  { word: "ATUN", hint: "Pez grande y rápido" },
  { word: "PEZESPADA", hint: "Pez con mandíbula alargada" },
  { word: "RAYA", hint: "Pez plano con cola larga" },
  { word: "TIBURON", hint: "Pez grande con dientes afilados" },
  { word: "BALLENA", hint: "Mamífero marino más grande" },
  { word: "DELFIN", hint: "Mamífero acuático inteligente" },
  { word: "ORCA", hint: "Ballena asesina" },
  { word: "FOCA", hint: "Mamífero acuático juguetón" },
  { word: "LEONMARINO", hint: "Mamífero acuático con melena" },
  { word: "PINGUINO", hint: "Ave que no vuela y vive en el hielo" },
  { word: "GAVIOTA", hint: "Ave marina común" },
  { word: "PELICANO", hint: "Ave con bolsa en el pico" },
  { word: "CUERVO", hint: "Ave negra inteligente" },
  { word: "LORO", hint: "Ave que puede imitar sonidos" },
  { word: "CANARIO", hint: "Ave pequeña y amarilla" },
  { word: "GORRION", hint: "Ave pequeña y común" },
  { word: "PAVO", hint: "Ave grande con cola en abanico" },
  { word: "COLIBRI", hint: "Ave pequeña que bate alas rápido" },
  { word: "BUHO", hint: "Ave nocturna con ojos grandes" },
  { word: "AGUILA", hint: "Ave rapaz de gran tamaño" },
  { word: "CISNE", hint: "Ave acuática elegante y blanca" },
  { word: "PATO", hint: "Ave acuática con pico ancho" },
  { word: "FLAMENCO", hint: "Ave rosada de patas largas" },
  { word: "CAMELLO", hint: "Animal del desierto con joroba" },
  { word: "ORNITORRINCO", hint: "Mamífero que pone huevos" },
  { word: "ARMADILLO", hint: "Animal con caparazón duro" },
  { word: "KOALA", hint: "Marsupial que vive en eucaliptos" },
  { word: "CEBRA", hint: "Animal con rayas blancas y negras" },
  { word: "HIPOPOTAMO", hint: "Animal grande que vive en ríos" },
  { word: "RINOCERONTE", hint: "Animal grande con cuerno" },
  { word: "LEON", hint: "Rey de la selva" },
  { word: "OSO", hint: "Animal grande y peludo" },
  { word: "LOBO", hint: "Animal salvaje similar al perro" },
  { word: "VAMPIRO", hint: "Ser nocturno que bebe sangre" },
  { word: "BRUJA", hint: "Mujer con poderes mágicos" },
  { word: "MAGO", hint: "Persona que hace trucos de magia" },
  { word: "HADA", hint: "Ser mágico pequeño con alas" },
  { word: "FANTASMA", hint: "Espíritu o aparición" },
  { word: "UNICORNIO", hint: "Caballo mitológico con cuerno" },
  { word: "DRAGON", hint: "Criatura mitológica que escupe fuego" },
];

export const WORDS: string[] = HANGMAN_WORDS.map(
  (hangmanWord) => hangmanWord.word
);
